ekf_localization_node:
  ros__parameters:
    frequency: 10.0
    sensor_timeout: 0.1
    two_d_mode: false
    publish_tf: true
    odom_frame: odom
    base_link_frame: tof_one
    world_frame: odom
    
    imu0: /bno055/imu
    imu0_config:  [false, false, false,   # X, Y, Z position
                   true,  true,  true,   # Roll, Pitch, Yaw
                   false, false, false,  # X, Y, Z velocity (don't use)
                   true,  true,  true,  # Roll, Pitch, Yaw velocity (don't use)
                   true,  true,  true,]  # Acceleration (not used)
    imu0_differential: false
    imu0_relative: true
    imu0_pose_rejection_threshold: 0.8
    imu0_twist_rejection_threshold: 0.5
    
    odom0: /tof_odom_one
    odom0_config: [true,  true,  true,   # X, Y, Z position
                   true,  true,  true,   # Roll, Pitch, Yaw
                   false, false, false,  # X, Y, Z velocity (don't use)
                   false, false, false,  # Roll, Pitch, Yaw velocity (don't use)
                   false, false, false]  # Acceleration (not used)
    odom0_differential: false
    odom0_relative: true
    odom0_pose_rejection_threshold: 3.0
    odom0_twist_rejection_threshold: 3.0
    odom0_process_noise_covariance: [0.05, 0.0, 0.0, 0.0, 0.0, 0.0,  
                               0.0, 0.05, 0.0, 0.0, 0.0, 0.0,  
                               0.0, 0.0, 0.05, 0.0, 0.0, 0.0,  
                               0.0, 0.0, 0.0, 0.1, 0.0, 0.0,  
                               0.0, 0.0, 0.0, 0.0, 0.1, 0.0,  
                               0.0, 0.0, 0.0, 0.0, 0.0, 0.1] 

    odom0_initial_estimate_covariance: [0.1, 0.0, 0.0, 0.0, 0.0, 0.0,  
                                  0.0, 0.1, 0.0, 0.0, 0.0, 0.0,  
                                  0.0, 0.0, 0.1, 0.0, 0.0, 0.0,  
                                  0.0, 0.0, 0.0, 0.1, 0.0, 0.0,  
                                  0.0, 0.0, 0.0, 0.0, 0.1, 0.0,  
                                  0.0, 0.0, 0.0, 0.0, 0.0, 0.1]
    
    # odom1: /tof_odom_two
    # odom1_config: [true,  true,  true,   # X, Y, Z position
    #                true,  true,  true,   # Roll, Pitch, Yaw
    #                false, false, false,  # X, Y, Z velocity (don't use)
    #                false, false, false,  # Roll, Pitch, Yaw velocity (don't use)
    #                false, false, false]  # Acceleration (not used)
    # odom1_differential: false
    # odom1_relative: true
    # odom1_pose_rejection_threshold: 3.0
    # odom1_twist_rejection_threshold: 3.0
    # odom1_process_noise_covariance: [0.05, 0.0, 0.0, 0.0, 0.0, 0.0,  
    #                            0.0, 0.05, 0.0, 0.0, 0.0, 0.0,  
    #                            0.0, 0.0, 0.05, 0.0, 0.0, 0.0,  
    #                            0.0, 0.0, 0.0, 0.1, 0.0, 0.0,  
    #                            0.0, 0.0, 0.0, 0.0, 0.1, 0.0,  
    #                            0.0, 0.0, 0.0, 0.0, 0.0, 0.1] 

    # odom1_initial_estimate_covariance: [0.1, 0.0, 0.0, 0.0, 0.0, 0.0,  
    #                               0.0, 0.1, 0.0, 0.0, 0.0, 0.0,  
    #                               0.0, 0.0, 0.1, 0.0, 0.0, 0.0,  
    #                               0.0, 0.0, 0.0, 0.1, 0.0, 0.0,  
    #                               0.0, 0.0, 0.0, 0.0, 0.1, 0.0,  
    #                               0.0, 0.0, 0.0, 0.0, 0.0, 0.1]

                                  